// <auto-generated />
using Bible.Proxy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bible.Proxy.Migrations
{
    [DbContext(typeof(BibleDBContext))]
    partial class BibleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bible.Proxy.Models.AmericanStandardVersion", b =>
                {
                    b.Property<string>("VerseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Scriptures");

                    b.HasKey("VerseId");

                    b.ToTable("AmericanStandardVersion");
                });

            modelBuilder.Entity("Bible.Proxy.Models.EnglishStandardVersion", b =>
                {
                    b.Property<string>("VerseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Scriptures");

                    b.HasKey("VerseId");

                    b.ToTable("EnglishStandardVersion");
                });

            modelBuilder.Entity("Bible.Proxy.Models.KingJamesVersion", b =>
                {
                    b.Property<string>("VerseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Scripture");

                    b.HasKey("VerseId");

                    b.ToTable("KingJamesVersion");
                });
#pragma warning restore 612, 618
        }
    }
}
